print("Date Calculation Utility")
print("**********************")
print("")
a=int(input("Enter Days     : "))
print("")
y=int(a/365)
bd=(a%365)
m=int(bd/30)
d=(bd%30)
print("Year                          :",y)
print("Months                     :",m)
print("Days                         :",d)
