print("Interest Calculation Utility")
print("*************************")
print("")
p=int(input("Principle          : "))
t=int(input("Time                : "))
r=int(input("Rate                 : "))
print("")
i=round(((p*t*r)/100),2)
print("Interest            :",i)
