print("Time Calculation Utility")
print("**********************")
print("")
a=int(input("Enter Time          : "))
print("")
h=int(a/3600)
bs=(a%3600)
m=int(bs/60)
s=(bs%60)
print("Hour                    :",h)
print("Minutes               :",m)
print("Seconds               :",s)
