print("Multiplication Utility")
print("********************")
print("")
a=int(input("Enter 1st Number  : " ))
b=int(input("Enter 2nd Number : " ))
print("")
c=(a*b)
print("Multiplication        :",c)
