print("Mathematics Calculation Utility")
print("*****************************")
print("")
a=int(input("Enter 1st Number         : " ))
b=int(input("Enter 2nd Number        : " ))
print("")
c=(a*b)
d=(a+b)
e=(c-d)
print("Product                          :",c)
print("Summation                    :",d)
print("Difference                      :",e)
