print("Mathematics Calculation Utility ")
print("********************************")
print("")
a=int(input("Enter 1st Number   :"))
b=int(input("Enter 2nd Number   :"))
print("")
c=(a+b)
d=(a-b)
e=(a*b)
f=int(a/b)
g=(a%b)
print("Summation Calculation              :", c)
print("Substraction Calculation           :", d)
print("Multiplication Calculation         :", e)
print("Quotient Calculation               :", f)
print("Remainder Calculation              :", g)
 
