print("Square Calculation Utility")
print("************************")
print("")
a=int(input("Enter Square Side           : "))
print("")
b=(a*a)
c=(4*a)
print("Area                                :",b)
print("Perimeter                        :",c)
