print("Rectangle Calculation Utility")
print("***************************")
print("")
a=int(input("Enter Length             :"))
b=int(input("Enter Breadth            :"))
print("")
c=(a*b)
d=2*(a+b)
print("Area                          :",c)
print("Perimeter                  :",d)
