print("Currency Calculation Utility")
print("**************************")
print("")
a=int(input("Enter Amount (Paisa)      : "))
print("")
r=int(a/100)
ba=(a%100)
print("Rupee                                :",r)
print("Balance                             :",ba)
