print("Class Calculation Utility")
print("**********************")
print("")
sname=input("Name             : ")
sclass=input("Class               : ")
rlno=int(input("Roll No           : "))
sec=input("section                 : ")
m1=int(input("English                : "))
m2=int(input("Bengali                : "))
m3=int(input("Mathematics       : "))
m4=int(input("Science                : "))
m5=int(input("History                : "))s
print("")
tot=(m1+m2+m3+m4+m5)
avg=(tot/5)
print("Name                 :",sname)
print("Class                  :",sclass)
print("Roll No               :",rlno)
print("Section               :",sec)
print("Total                  :",tot)
print("Average             :",avg)
