print("Size Calculation Utility")
print("*********************")
print("")
a=int(input("Enter centimeter       : "))
print("")
p=(a/2.54)
ft=int(p/12)
inch=int(p%12)
print("Feet                 :",ft)
print("Inch                 :",inch)
