print("Mathematics Calculation Utility")
print("*****************************")
print("")
a=int(input("Enter  Number        : "))
print("")
b=(2*a)
c=(3*a)
d=(a*a)
e=(a*a*a)
print("Twice                       :",b)
print("Thrice                      :",c)
print("Square                     :",d)
print("Cube                        :",e)
