print("Amount Calculation Utility")
print("*************************")
print("")
a=int(input("Enter 1st Quantity        : "))
b=int(input("Enter 1st Rate            : "))
print("")
c=int(input("Enter 2nd Quantity       : "))
d=int(input("Enter 2nd Rate           : "))
print("")
e=int(input("Enter 3nd Quantity         : "))
f=int(input("Enter 3nd Rate             : "))
g=(a*b)
h=(c*d)
i=(e*f)
j=(g+h+i)
print("Amount                          :",g)
print("Amount                          :",h)
print("Amount                          :",i)
print("Bill Amount                     :",j)

