print("Fence Calculation Utility")
print("***********************")
print("")
a=int(input("Enter Length                  : "))
b=int(input("Enter Breadth                : "))
c=int(input("Enter Fencing Rate        : "))
d=int(input("Enter Carpeting Rate    : "))
print("")
area=(a*b)
peri=(2*(a+b))
f=(peri*c)
c=(area*d)
add=(f+c)
print("Area                              :",area)
print("Perimeter                      :",peri)
print("")
print("")
print("Fencing Cost                       :",f)
print("Carpeting Cost                    :",c)
print("Total Cost                           :",add)
