print("Size Calculation Utility")
print("*********************")
print("")
a=int(input("Enter Feet              : "))
b=int(input("Enter Inch              : "))
print("")
f=(a*30.48)
i=(b*2.54)
cm=(f+i)
print("Centimeter             :",cm)
